# 这个环境在运行greedy_old.py时明显较慢：
# - 正常输出：Epoch 1: Best acf is 0.19...;duration is 12+s
# - 较慢输出： Epoch 1: Best acf is 0.27...;duration is 57+s
# 原因未知

name: tmp2
channels:
  - conda-forge
  - defaults
dependencies:
  - branca=0.6.0
  - folium=0.14.0
  - jinja2=3.1.2
  - matplotlib-base=3.5.3
  - numpy==1.19.2
  - pandas==1.1.5
  - pip=21.2.2
  - python=3.7.16
  - pyyaml=5.4.1
  - scikit-learn==0.24.2
  - seaborn=0.11.2
  - setuptools=58.0.4
  - shapely=1.8.0
  - wheel=0.37.1
  - pip:
    - gputil==1.4.0
    - matplotlib==3.3.0
    - networkx==2.5.1
    - nni==2.6.1
    - scipy==1.2.1
    - statsmodels==0.12.2
